all:
	# gcc main_TP3.c -lm -O3 -o o.o; ./o.o
	gcc main_TP3_exam.c -lm -O3 -o o.o; ./o.o
3:
	gcc main_TP3.c -lm -O3 -o o.o;
2:
	gcc main_TP2_a_remplir.c -lm -O3 -o o.o; ./o.o
1:
	gcc main_TP1.c -lm -O3 -o o.o;