all:
	gcc main.c -Wdate-time -D_FORTIFY_SOURCE=2 -I/usr/lib/petscdir/petsc3.12/x86_64-linux-gnu-real/include -L/usr/lib/petscdir/petsc3.12/x86_64-linux-gnu-real/lib -lpetsc_real -pthread -I/usr/lib/x86_64-linux-gnu/openmpi/include -I/usr/lib/x86_64-linux-gnu/openmpi/include/openmpi -L/usr/lib/x86_64-linux-gnu/openmpi/lib -lmpi -o executable 
