a=open("localbiblio.bib", mode="r")
a2=open("localbiblio-out.bib", mode="w")
# https://woodward.library.ubc.ca/woodward/research-help/journal-abbreviations/
for i in range(0,2000):
	a1=a.readline()
#	print(a1[0:7])
#	if a1[0:8]=="@article":
#		print(a1[0:8])
	if a1[0:9]=="  journal":
		print(a1)
		a1=a1.replace("Annu. Rev. Fluid Mech.","Ann. Rev. Fluid Mech.")
		a1=a1.replace("Annual Review of Fluid Mechanics","Ann. Rev. Fluid Mech.")
		a1=a1.replace("Annual review of fluid mechanics","Ann. Rev. Fluid Mech.")
		a1=a1.replace("Comptes Rendus de l'Acad{\\'e}mie des Sciences-Series IIB-Mechanics-Physics-Chemistry-Astronomy","C. R. Acad. Sci., Ser. II  b ")
		a1=a1.replace("Computers \& fluids","Comput. Fluids")
		a1=a1.replace("Experiments in Fluids","Exp. Fluids")
		a1=a1.replace("European Journal of Mechanics-B/Fluids","Eur. J.~Mech. {\em B\/}/Fluids")
		a1=a1.replace("Fluid Dynamics Research","Fluid Dyn. Res.")
		a1=a1.replace("International Journal for Numerical Methods in Fluids","Int. J. Numer. Meth. Fluids")
		a1=a1.replace("Journal of Fluid Mechanics","J. Fluid Mech.")
		a1=a1.replace("Numerical Heat Transfer, Part A: Applications","Numer. Heat Transfer A")
		a1=a1.replace("Philosophical Transactions of the Royal Society A","Philos. Trans. Royal Soc. A")
		a1=a1.replace("Physical Review E","Phys. Rev. E")
		a1=a1.replace("Physical Review E—Statistical, Nonlinear, and Soft Matter Physics","Phys. Rev. E")
		a1=a1.replace("Physical Review Fluids","Phys. Rev. Fluids")
		a1=a1.replace("Physics Review Letters","Phys. Rev. Lett.")
		a1=a1.replace("Physics of Fluids","Phys. Fluids ")
		a1=a1.replace("The Physics of fluids","Phys. Fluids ")
		a1=a1.replace("The quarterly journal of mechanics and applied mathematics","Q. J. Mech. Appl. Math.")
		print(a1)
#	a2.write(a1)

	if a1[0:7]=="  title":
		print(a1)
		a1=a1.replace("Batchelor ","{B}atchelor ")
		a1=a1.replace("Chebyshev","{C}hebyshev")
		a1=a1.replace("Couette","{C}ouette")
		a1=a1.replace("Ekman","{E}kman")
		a1=a1.replace("Taylor","{T}aylor")
		print(a1)
#	a2.write(a1)

	if a1[0:8]=="  author":
		print(a1)
		a1=a1.replace("Avila, Marc","Avila, M.")
		a1=a1.replace("Batchelor, George K","Batchelor, G. K.")
		a1=a1.replace("Bontoux, Patrick","Bontoux, P.")
		a1=a1.replace("Boujo, Edouard","Boujo, E.")
		a1=a1.replace("Busse, Friedrich H","Busse, F. H.")
		a1=a1.replace("Chauve, MP","Chauve, M. P.")
		a1=a1.replace("Chauve, Marie-Pierre","Chauve, M. P.")
		a1=a1.replace("Chomaz, Jean-Marc","Chomaz, J. M.")
		a1=a1.replace("Clever, Richard M","Clever, R. M.")
		a1=a1.replace("Cousin-Rittemard, Nathalie","  Cousin-Rittemard, N.")
		a1=a1.replace("Cross, Michael","Cross, M.")
		a1=a1.replace("Cros, Anne","Cros, A.")
		a1=a1.replace("Daube, Olivier","Daube, O.")
		a1=a1.replace("Brady, John F","B")
		a1=a1.replace("Brady, John F and Durlofsky, Louis}","Daube, O.")
		a1=a1.replace("Del Arco, E Crespo","Crespo Del Arco, E.")
		a1=a1.replace("Dijkstra, D ","Dijkstra, D. ")
		a1=a1.replace("Van Heijst, GJF","Van Heijst, G. J. F.")
		a1=a1.replace("Crespo Del Arco, Emilia","Crespo Del Arco, E.")
		a1=a1.replace("Do, Younghae","Do, Y.")
		a1=a1.replace("Du, Qiang","Du, Q.")
		a1=a1.replace("Ducimeti{\\`e}re, Yves-Marie","  Ducimeti{\`e}re, Y. M.")
		a1=a1.replace("Duguet, Yohann","Duguet, Y.")
		a1=a1.replace("Eckhardt, Bruno","Eckhardt, B.")
		a1=a1.replace("Faisst, Holger","Faisst, H.")
		a1=a1.replace("Faller, Alan J","Faller, A. J.")
		a1=a1.replace("Floriani, Elena","Floriani, E.")
		a1=a1.replace("Gallaire, Fran{\c{c}}ois","Gallaire, F.")
		a1=a1.replace("Gauthier, G","Gauthier, G.")
		a1=a1.replace("Gelfgat, A Yu","Gelfgat, A. Y.")
		a1=a1.replace("Gesla, Artur","Gesla, A.")
		a1=a1.replace("Gondret, P","Gondret, P.")
		a1=a1.replace("Greenside, Henry","Greenside, H.")
		a1=a1.replace("Greenspan, Harvey Philip","Greenspan, H. P.")
		a1=a1.replace("Guckenheimer, John","Guckenheimer, J.")
		a1=a1.replace("Hof, Bjorn","Hof, B.")
		a1=a1.replace("Holmes, Philip","Holmes, P.")
		a1=a1.replace("Ishida, Takahiro","Ishida, T.")
		a1=a1.replace("Launder, Brian","Launder, B.")
		a1=a1.replace("Le Gal, Patrice","Le Gal, P.")
		a1=a1.replace("Le Qu{\\'e}r{\\'e}, Patrick","Le Qu{\\'e}r{\\'e}, P.")
		a1=a1.replace("Li, Siyi","Li, S.")
		a1=a1.replace("Lima, Ricardo","Lima, R.")
		a1=a1.replace("Lopez, Juan M","Lopez, J. M.")
		a1=a1.replace("Marques, Francisco","Marques, F.")
		a1=a1.replace("Martin Witkowski, Laurent","Martin Witkowski, L.")
		a1=a1.replace("Martinand, D","Martinand, D.")
		a1=a1.replace("Nagata, Masato","Nagata, M.")
		a1=a1.replace("Net, Marta","Net, M.")
		a1=a1.replace("Poncet, S{\\'e}bastien","Poncet, S.")
		a1=a1.replace("Quere, Patrick Le","Le Qu{\\'e}r{\\'e}, P.")
		a1=a1.replace("Qu{\\'e}r{\\'e}, Patrick Le","Le Qu{\\'e}r{\\'e}, P.")
		a1=a1.replace("Rabaud, M","Rabaud, M.")
		a1=a1.replace("Rubio, Antonio M","Rubio, A. M.")
		a1=a1.replace("Sanchez Umbria, Juan","Sanchez Umbria, J.")
		a1=a1.replace("Schneider, Tobias M","Schneider, T. M.")
		a0=a1; a1=a1.replace("Schouveiler, Lionel","  Schouveiler, L")
		a1=a1.replace("Schouveiler, L","  Schouveiler, L.")

		a0=a1; a1=a1.replace("Serre, Eric","Serre, {\\'E}.")
		a1=a1.replace("Serre, E","Serre, {\\'E}.")
		a1=a1.replace("Serre, {\\'E}ric","Serre, {\\'E}.")
		a1=a1.replace("Takeda, Y","Takeda, Y.")
		a1=a1.replace("Tsukahara, Takahiro","Tsukahara, T.")
		a1=a1.replace("Veronis, George","Veronis, G.")
		a1=a1.replace("Viaud, B","Viaud, B.")
		a1=a1.replace("Wang, Zhicheng","Wang, Z.")
		a1=a1.replace("Westerweel, Jerry","Westerweel, J.")
		a1=a1.replace("Whitehead, John A","Whitehead, J. A.")
		a1=a1.replace("Witkowski, Laurent Martin","Martin Witkowski, L.")
		a1=a1.replace("Xie, Lei","Xie, L.")
		a1=a1.replace("Xie, Yaguang","  Xie, Y.")
		a1=a1.replace("Xin, Shihe","Xin, S.")
		print(a1)
	a2.write(a1)


